.gitignore, package-lock.json, package.json, src/App.tsx, src/components/Login/loginpage.tsx, src/components/LoginPage/loginpage.css, src/components/LoginPage/loginpage.tsx, src/components/SignUpPage/SignUpPage.tsx, src/firebase/firebase.ts, src/main.tsx, tsconfig.json
Note that you have to add the firebaseConfig.ts into the firebase folder to get this to work
=> Setup firebase + login and create account functionality

package-lock.json, package.json, src/components/NavigationBar/NavigationBar.tsx
Merging Nav bar into main
Partially Resolves #10
=> Merge Frontend setup nav bar into Main

.github/pull_request_template.md, package-lock.json, src/App.tsx, src/components/NavigationBar/NavigationBar.tsx, src/pages/DiscussionPage/DiscussionPage.tsx, src/pages/HomePage/HomePage.tsx, src/pages/LevelSelectPage/LevelSelectPage.tsx, src/pages/LoginPage/LoginPage.tsx, src/pages/QuestionPage/QuestionPage.css, src/pages/QuestionPage/QuestionPage.tsx, src/pages/SignUpPage/SignUpPage.tsx
=> Fix Routing

src/components/LevelDescription.tsx
Changes the 'Start problem button' to GreenButton component
Resolves #54 
This PR does the following
- Adds GreenButton component for starting the problem to the level description
=> Changed the Start problem button to button component

.github/pull_request_template.md, package-lock.json, package.json, src/components/TestPage.tsx, src/firebase/db/dummyData.ts, src/firebase/db/initDb.ts, src/firebase/enums.ts, src/firebase/firebase.ts, src/models/types.ts, tsconfig.json
Resolves #48 
This PR does the following
=> 48 inserting content to db

src/App.tsx, src/components/ProtectedRoute/index.tsx, src/context/UserContext.ts
=> feat: redirect authenticated users to login

src/pages/QuestionPage/QuestionPage.tsx
Resolves #68 
Can test by setting goal graph to initial graph in graph application props
=> fix: only submit successfully when complete

src/components/GitGraph/RoundCustomNode.tsx, src/components/GitGraph/index.tsx, src/components/GitGraph/initial-firebase-nodes-edges.ts, src/components/GraphApplication/index.tsx, src/components/Terminal/index.tsx
Resolves #[82]
- [change color of nodes when nodes are pushed]
- [ label head]
=> color change for git push and head

src/App.css, src/App.tsx, src/components/NavigationBar/NavigationBar.module.css, src/components/NavigationBar/NavigationBar.tsx, src/components/Terminal/index.tsx, src/index.css, src/pages/LandingPage/landingpage.module.css, src/pages/LandingPage/landingpage.tsx, src/pages/LoginPage/LoginPage.tsx, src/pages/QuestionPage/QuestionPage.module.css, src/pages/QuestionPage/QuestionPage.tsx, src/pages/SignUpPage/SignUpPage.tsx
=> fix: question page styling

src/components/GreenButton/GreenButton.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/QuestionEndModal/QuestionEndModal.tsx, src/pages/LoginPage/LoginPage.tsx, src/pages/SignUpPage/SignUpPage.tsx
=> Add user tofirebase

src/data/dummyData.ts
Adds learning outcomes for the checkout and branch level
Resolves #70 
=> Add learning outcome for checkout and branch

src/components/GitGraph/index.tsx, src/components/GraphApplication/index.tsx, src/components/Terminal/index.tsx, src/models/types.ts
=> 108 graph schema overhaul

src/models/types.ts
=> Added fields for description and initialCmds

src/components/GitGraph/index.tsx, src/components/GraphApplication/index.tsx
Resolves #[105]
- [ display branch table for checkout]
=> branch table

src/data/dummyData.ts
Added learning outcome for merge level and changed level 1 tags and difficulty back to commit and push and easy difficulty
Resolves #104 
TODO:
=> Add learning outcome for merge level

src/components/Terminal/index.tsx
=> feat: add git merge

src/components/Terminal/index.tsx
=> fix: push should push all previous nodes

src/data/dummyData.ts
=> fix: update scaffolded commands

src/pages/QuestionPage/QuestionPage.tsx
=> fix: missing question graphs

src/components/GitGraph/CommitNode.tsx, src/components/GitGraph/Layout.ts
=> fix: make nodes closer

src/HelpBar/HelpBar.tsx, src/HelpBar/HintToolTip.tsx, src/components/GraphApplication/index.tsx, src/pages/QuestionPage/QuestionPage.tsx
=> Stopped hard coded hints

src/data/dummyData.ts
Resolves #141  #144 #145 
Bug: 
Bug found when switching between levels with the discussion up
Sample answers concatenate
=> 141 git merge instructions

src/components/QuestionEndModal/QuestionEndModal.tsx, src/data/dummyData.ts, src/models/types.ts
=> Update end modal

src/data/dummyData.ts, src/pages/QuestionPage/QuestionDescription.module.css
=> hide scrollbar

src/components/GitGraph/index.tsx
Resolves #[N/A]
- [ add headers for branch data]
=> added branch table header

src/components/LevelDiscussion/LevelDiscussion.tsx
Resolves #[Ticket num]
- [ cmd duplication fix]
=> cmd duplication fix

src/components/LevelDiscussion/LevelDiscussion.tsx
=> fix: hiding discussion before attempting question

src/components/GraphApplication/index.tsx, src/components/Terminal/index.tsx
=> refactor: improve scaffolding
